### ISSUE TITLE
 CPU consumption after deployment

### ISSUE THREAD

**Issue by sohhamm** [colbyfayock/next-leaflet-starter#1]
I'm using this code template for my application(large ecommerce site) but after I deploy to AWS beanstalk the memory leaks and CPU consumption hit 98%.
I also get this firefox warning 
`
Will-change memory consumption is too high. Budget limit is the document surface area multiplied by 3 (304704 px). Occurrences of will-change over the budget will be ignored.
`

**Comment by colbyfayock** [comment]
hey @sohhamm do you experience the same memory issues with this page? https://react-leaflet.js.org/

the package versions aren't 100% up to date, so that might help, but  curious if it's an issue with the starter or React Leaflet / Leaflet
