### ISSUE TITLE
Update to react-leaflet 4.0.0+

### ISSUE THREAD

**Issue by theGOTOguy** [colbyfayock/next-leaflet-starter#2]
`MapConsumer` was [removed in react-leaflet 4.0.0](https://github.com/PaulLeCam/react-leaflet/blob/master/CHANGELOG.md#v400-2022-04-18), so that your example works in react-leaflet 3.x but not 4.x.

I found this example enormously helpful, and I'm sure others have and will in the future.  If you like, I can submit a PR updating your starter kit.

**Comment by colbyfayock** [comment]
thanks @theGOTOguy i havent been keeping up with this, that would be great

could you look into upgrading the other packages while you're in here?

thanks
